version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:django_project
    ports:
      - 8000:8000
    image: backend:django_project
    container_name: backend_container
    command: python manage.py runserver 0.0.0.0:8000