# Generated by Django 3.2.15 on 2022-09-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0002_auto_20220913_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyvoucher',
            name='products',
        ),
    ]
