# Generated by Django 3.2.15 on 2022-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_remove_buyvoucher_products'),
        ('products', '0002_auto_20220914_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyvoucher',
            name='articles',
            field=models.ManyToManyField(to='products.Article'),
        ),
    ]
