# Generated by Django 3.2.15 on 2022-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0004_buyvoucher_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
    ]
