# Generated by Django 3.2.15 on 2022-09-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_init_agents_permissions'),
        ('transactions', '0002_expenses_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
