# Generated by Django 3.2.15 on 2022-09-15 17:47

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('phone_first', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_second', models.CharField(blank=True, max_length=16, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('fiscal_id', models.CharField(blank=True, max_length=16, null=True)),
                ('trade_registry', models.CharField(blank=True, max_length=32, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('balance_initial', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('total', models.PositiveIntegerField(default=base.models.Voucher.calculate_total)),
                ('number', models.CharField(max_length=32)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('rest', models.PositiveIntegerField(default=base.models.Voucher.calculate_rest)),
                ('with_debt', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sells.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellVoucherDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.article')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sells.sellvoucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['created_at'],
                'abstract': False,
            },
        ),
    ]
