# Generated by Django 3.2.15 on 2022-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellvoucher',
            name='rest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellvoucher',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
