# Generated by Django 3.2.15 on 2022-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance_initial',
            field=models.IntegerField(default=0),
        ),
    ]
