# Generated by Django 3.2.15 on 2022-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220914_0049'),
        ('sells', '0002_auto_20220913_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellvoucher',
            name='products',
        ),
        migrations.AddField(
            model_name='sellvoucher',
            name='articles',
            field=models.ManyToManyField(to='products.Article'),
        ),
    ]
