# Generated by Django 3.2.15 on 2022-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_auto_20220914_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
