# Generated by Django 3.2.15 on 2022-09-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'get_latest_by': ['created_at'], 'ordering': ['-created_at']},
        ),
    ]
