# Generated by Django 3.2.15 on 2022-09-13 00:47

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sells', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('total', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=32)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('rest', models.PositiveIntegerField(default=base.models.Voucher.calculate_rest)),
                ('with_debt', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sells.client')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
