# Generated by Django 3.2.15 on 2022-09-20 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_init_agents_permissions'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=32)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('rest', models.PositiveIntegerField(default=0)),
                ('with_debt', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleVoucherDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.article')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pos.salevoucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['created_at'],
                'abstract': False,
            },
        ),
    ]
