# Generated by Django 3.2.15 on 2022-09-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_init_agents_permissions'),
        ('pos', '0002_auto_20220915_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucher',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
