# Generated by Django 3.2.15 on 2022-09-14 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reference', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_minimum', models.PositiveIntegerField(default=0)),
                ('stock_negative', models.BooleanField(default=False)),
                ('margin', models.PositiveIntegerField(default=0)),
                ('buy_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RenameModel(
            old_name='ProductFamily',
            new_name='ArticleFamily',
        ),
        migrations.AlterModelOptions(
            name='articlefamily',
            options={'get_latest_by': ['created_at'], 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'get_latest_by': ['created_at'], 'ordering': ['-created_at']},
        ),
    ]
