# Generated by Django 3.2.15 on 2022-09-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_salevoucher_articles'),
        ('sells', '0003_auto_20220914_0049'),
        ('products', '0002_auto_20220914_0049'),
        ('buys', '0004_buyvoucher_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.articlebrand'),
        ),
        migrations.AddField(
            model_name='article',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.articlefamily'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit'),
        ),
    ]
