# Generated by Django 3.2.15 on 2022-09-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220914_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefamily',
            options={'verbose_name_plural': 'Article families'},
        ),
    ]
